# Generated by Django 3.2.3 on 2021-05-25 07:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PetModel',
            fields=[
                ('Id', models.BigAutoField(primary_key=True, serialize=False)),
                ('petName', models.CharField(max_length=256)),
                ('petImage', models.ImageField(upload_to='')),
                ('Created', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
    ]
