# Generated by Django 3.2.3 on 2021-05-26 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PETApp', '0003_alter_petmodel_petimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='petmodel',
            name='amount',
            field=models.IntegerField(default='0'),
        ),
        migrations.AddField(
            model_name='petmodel',
            name='category',
            field=models.CharField(default='non', max_length=256),
        ),
        migrations.AddField(
            model_name='petmodel',
            name='type',
            field=models.CharField(default='non', max_length=256),
        ),
    ]
